spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/jsonDate
    password: free
  main:
    web-application-type: none
file:
  path: C:\Users\andrei.lisa\Folder\doc1.json
reader:
  keys:
    entityName: object
    entityTypeDescription: object
    nzbn: object
    lastUpdatedDate: object
    sourceRegisterUniqueIdentifier: object
    industryClassification: array
    physicalAddress: array
    registeredAddress: array
    roles: array
server:
  error:
    whitelabel:
      enabled: 'false'
json:
  element:
    object,
    name,
    object,
    name,
    array

